name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Manual deployment
        run: echo "Deployment is manually gated. SSH to droplet and run docker compose pull && docker compose up -d"
